service: vigil-api

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: us-east-1
  memorySize: 256
  timeout: 10

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  exclude:
    - ./**
  include:
    - ./rds-combined-ca-bundle.pem
    - ./bin/**

functions:
  api:
    handler: bin/main
    environment:
      STAGE: prod
      DB_HOST: <host>
      DB_PORT: <port>
      DB_USER: api
      DB_PASS: <pass>
      DB_SSLMODE: verify-full
      DB_SSL_ROOT_CERT: rds-combined-ca-bundle.pem
      DB_NAME: vigil
    events:
      - http:
          path: /{proxy+}
          method: any
